llm_service:
  port: 10000
  llm_models:
    gpt-3.5-turbo-0125:
      provider: "openai"
      api_key: ""
      base_url: ""
      temperature: 0.7
      max_tokens: 1024
      format: ["openai"]

    gpt-4-turbo:
      provider: "openai"
      api_key: ""
      base_url: ""
      temperature: 0.7
      max_tokens: 1024
      format: ["openai"]

    gpt-4o:
      provider: "openai"
      api_key: ""
      base_url: ""
      temperature: 0.7
      max_tokens: 1024
      format: ["openai"]

    gpt-4o-mini:
      provider: "openai"
      api_key: ""
      base_url: ""
      temperature: 0.7
      max_tokens: 1024
      format: ["openai"]

    deepseek-chat:
      provider: "deepseek"
      api_key: ""
      base_url: "https://api.deepseek.com"
      temperature: 0.7
      max_tokens: 1024
      format: ["openai"]

    moonshot-v1-8k:
      provider: "kimi"
      api_key: ""
      base_url: "https://api.moonshot.cn/v1"
      temperature: 0.7
      max_tokens: 1024
      format: ["openai"]