llm_server:
  model: ""
  host: ""
  port: 10000

home_assistant:
  host: "0.0.0.0" # must be in the same device as the client
  port: 8123
  token: ""
  config_path: ""

porcupine:
  access_key: ""
  keywords: []
  keyword_paths: ["ppn/***"]
  sensitivities: []

tencent:
  appid: ""
  secret_id: ""
  secret_key: ""

web_ui:
  port: 8501